version: '3.7'

services:
  zookeeper:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

networks:
  kafka_net:
    driver: bridge
